### ISSUE TITLE
Show added date in comments

### ISSUE THREAD

**Issue by asanka-herath** [OpenArchitex/OpenLearnr#534]
Suggestions - 
+ display the time/date when someone posted a comment for a video. 
+ Ideally, the time of the comment should be converted to the time zone in the user viewing it.

**Comment by SudharakaP** [comment]
@asanka-herath : Isn't the date and time already displayed? 😃 

![image](https://user-images.githubusercontent.com/12435965/103367739-bcdd0900-4a7a-11eb-896c-670afc081423.png)

**Comment by asanka-herath** [comment]
Forgot to tell you it is for the admin view page :)  By the way, it's not a
priority.
[image: image.png]

**Comment by SudharakaP** [comment]
@asanka-herath : I did a quick fix to include the timestamp in front of the comments in the admin page. 😄 

![image](https://user-images.githubusercontent.com/12435965/103394887-0ad82800-4ae0-11eb-9b65-6cb7a2d6fc50.png)

**Comment by asanka-herath** [comment]
Awesome, thanks!
